version: '3'

services:

  logstash:
    build:
      context: ./docker/logstash
    volumes: 
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:2.3

  kibana:
    image: kibana:4.5.0
    ports:
      - "5601:5601"

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./public:/usr/share/nginx/html/
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/sites:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
